export const FETCH_LIST_SEAT_REQUEST = 'FETCH_LIST_SEAT_REQUEST'
export const FETCH_LIST_SEAT_SUCCESS = 'FETCH_LIST_SEAT_SUCCESS'
export const FETCH_LIST_SEAT_FAILED = 'FETCH_LIST_SEAT_FAILED'
//
export const SELECT_TICKER = 'SELECT_TICKER'
//
export const POST_DATVE_REQUEST = 'POST_DATVE_REQUEST'
export const POST_DATVE_SUCCESS = 'POST_DATVE_SUCCESS'
export const POST_DATVE_FAILED = 'POST_DATVE_FAILED'
export const DAT_VE_HOAN_TAT = 'DAT_VE_HOAN_TAT'