//Banner type
export const FETCH_BANNER_REQUEST = 'FETCH_BANNER_REQUEST'
export const FETCH_BANNER_SUCCESS = 'FETCH_BANNER_SUCCESS'
export const FETCH_BANNER_FAILED = 'FETCH_BANNER_FAILED'
//Movie Page
export const FETCH_MOVIEPAGE_REQUEST = 'FETCH_MOVIEPAGE_REQUEST'
export const FETCH_MOVIEPAGE_SUCCESS = 'FETCH_MOVIEPAGE_SUCCESS'
export const FETCH_MOVIEPAGE_FAILED = 'FETCH_MOVIEPAGE_FAILED'
//All Movie
export const FETCH_ALLMOVIE_REQUEST = 'FETCH_ALLMOVIE_REQUEST'
export const FETCH_ALLMOVIE_SUCCESS = 'FETCH_ALLMOVIE_SUCCESS'
export const FETCH_ALLMOVIE_FAILED = 'FETCH_ALLMOVIE_FAILED'
//Change Page
export const CHANGE_PAGE_PREV = 'CHANGE_PAGE_PREV'
export const CHANGE_PAGE_NEXT = 'CHANGE_PAGE_NEXT'
//Add Movie
export const ADD_MOVIEIMG_REQUEST = 'ADD_MOVIEIMG_REQUEST'
export const ADD_MOVIEIMG_SUCCESS = 'ADD_MOVIEIMG_SUCCESS'
export const ADD_MOVIEIMG_FAILED = 'ADD_MOVIEIMG_FAILED'
// Movie Info
export const FETCH_MOVIEINFO_REQUEST = "FETCH_MOVIEINFO_REQUEST"
export const FETCH_MOVIEINFO_SUCCESS = "FETCH_MOVIEINFO_SUCCESS"
export const FETCH_MOVIEINFO_FAILED = "FETCH_MOVIEINFO_FAILED"
//update movie
export const UPDATE_MOVIE_REQUEST = 'UPDATE_MOVIE_REQUEST'
export const UPDATE_MOVIE_SUCCESS = 'UPDATE_MOVIE_SUCCESS'
export const UPDATE_MOVIE_FAILED = 'UPDATE_MOVIE_FAILED'
//delete movie
export const DELETE_MOVIE_REQUEST = 'DELETE_MOVIE_REQUEST'
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS'
export const DELETE_MOVIE_FAILED = 'DELETE_MOVIE_FAILED'
