export const FETCH_INFO_SHOWTIMES_REQUEST = 'FETCH_INFO_SHOWTIMES_REQUEST'
export const FETCH_INFO_SHOWTIMES_SUCCESS = 'FETCH_INFO_SHOWTIMES_SUCCESS'
export const FETCH_INFO_SHOWTIMES_FAILED = 'FETCH_INFO_SHOWTIMES_FAILED'
//Get he thong rap
export const FETCH_HE_THONG_RAP_REQUEST = "FETCH_HE_THONG_RAP_REQUEST"
export const FETCH_HE_THONG_RAP_SUCCESS = "FETCH_HE_THONG_RAP_SUCCESS"
export const FETCH_HE_THONG_RAP_FAILED = "FETCH_HE_THONG_RAP_FAILED"
//GET CUM RAP
export const FETCH_CUM_RAP_REQUEST = 'FETCH_CUM_RAP_REQUEST'
export const FETCH_CUM_RAP_SUCCESS = 'FETCH_CUM_RAP_SUCCESS'
export const FETCH_CUM_RAP_FAILED = 'FETCH_CUM_RAP_FAILED'
//Tao lich chieu
export const POST_GREATE_SHOWTIME_REQUEST = 'POST_GREATE_SHOWTIME_REQUEST'
export const POST_GREATE_SHOWTIME_SUCCESS = 'POST_GREATE_SHOWTIME_SUCCESS'
export const POST_GREATE_SHOWTIME_FAILED = 'POST_GREATE_SHOWTIME_FAILED'
